debug: false
map:
  color: 0
  name: '&dMagic Map'
render:
  players: true
  playerNames: true
  entities: false
  async: false
give:
  enabled: false
  persist: true
  message: '&eYou received a MagicMap!'
WorldNames:
  default: cavetale.com
  world: Survival
  world_nether: Nether
  world_the_end: End
EnableCaveView:
  default: true
  world_the_end: false