debug: false
map:
  color: 0
  name: '&dMagic Map'
render:
  # seconds
  cooldown: 5
  # always refresh after x seconds
  refresh: 30
  # wait x seconds after (far) teleport
  teleportCooldown: 5
cursor:
  enabled: true
  players: true
  playerNames: true
  markerArmorStands: true
  entities: false
  ticks: 10 # in ticks
  coordinates: true
give:
  enabled: false
  persist: true
  message: '&eYou received a MagicMap!'
WorldNames:
  default: cavetale.com
  world: Survival
  world_nether: Nether
  world_the_end: End
EnableCaveView:
  default: true
  world_the_end: false