debug: false
map:
  color: 0
  name: '&dMagic Map'
cursor:
  players: true
  markerArmorStands: true
  entities: false
  ticks: 10 # in ticks
give:
  enabled: false
  persist: true
  message: '&eYou received a MagicMap!'
WorldNames:
  default: cavetale.com
  world: Survival
  world_nether: Nether
  world_the_end: End
EnableCaveView:
  default: true
  world_the_end: false