debug: false
map:
  color: 0
  name: '&dMini Map'
give:
  enabled: false
  persist: true
  message: '&eYou received a MiniMap!'
WorldNames:
  default: cavetale.com
  world: Survival
  world_nether: Nether
  world_the_end: End
EnableCaveView:
  default: true
  world_the_end: false