debug: false
map:
  color: 0
  name: '&dMagic Map'
render:
  cooldown: 5 # seconds
  refresh: # alwyas refresh after x seconds
  teleportCooldown: 5 # wait x seconds after (far) teleport
cursor:
  players: true
  playerNames: true
  markerArmorStands: true
  entities: false
  ticks: 10 # in ticks
give:
  enabled: false
  persist: true
  message: '&eYou received a MagicMap!'
WorldNames:
  default: cavetale.com
  world: Survival
  world_nether: Nether
  world_the_end: End
EnableCaveView:
  default: true
  world_the_end: false