name: MagicMap
description: Dynamic map item
author: StarTux
version: 0.1
api-version: 1.17
website: https://github.com/StarTux/MagicMap
main: com.cavetale.magicmap.MagicMapPlugin
depend: []
softdepend: [Mytems]
commands:
  magicmap:
    description: Debug command
    permission: magicmap.magicmap
    usage: |-
      /magicmap reload - Reload config
      /magicmap debug - Debug stuff
      /magicmap give [player] - Spawn map for player
      /magicmap rerender - Trigger map rerender
permissions:
  magicmap.magicmap:
    description: Use the /magicmap command
    default: op
  magicmap.receive:
    description: Be eligible for a free MagicMap.
    default: op