name: MagicMap
description: Dynamic map item
author: StarTux
version: 0.1
api-version: 1.13
website: https://cavetale.com
main: com.cavetale.magicmap.MagicMapPlugin
depend: []
softdepend: []
commands:
  magicmap:
    description: Debug command
    permission: magicmap.magicmap
    usage: |-
      /magicmap reload - Reload config
      /magicmap debug - Debug stuff
permissions:
  magicmap.magicmap:
    description: Use the /magicmap command
    default: op
  magicmap.receive:
    description: Be eligible for a free MagicMap.
    default: false