name: MagicMap
description: Dynamic map item

version: 0.1
api-version: '1.20'

author: StarTux
website: https://github.com/StarTux/MagicMap
main: com.cavetale.magicmap.MagicMapPlugin

depend:
- Core
- Mytems
- Connect
softdepend:
- Area
- Webserver
- Home

commands:

  magicmap:
    description: Debug command
    permission: magicmap.magicmap
    usage: /magicmap

permissions:

  magicmap.magicmap:
    description: Use the /magicmap command
    default: op

  magicmap.receive:
    description: Be eligible for a free MagicMap.
    default: op